name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      ALLOWED_AUTHOR: Urias-T

    steps:
      - name: Validate Pusher
        if: ${{ github.actor != env.ALLOWED_AUTHOR }}
        run: |
          echo "Only the user with username ${ALLOWED_AUTHOR} is allowed to push to the main branch."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          service_account: ${{ secrets.GCP_SA }}

      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: .
          destination: ${{ secrets.GCP_BUCKET }}
