name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to Google Cloud Storage
        uses: GoogleCloudPlatform/github-actions/upload-to-gcs@v0.2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          bucket: ${{ secrets.GCP_BUCKET }}
          source: .
