# This workflow ensure s that I (Triumph) am the only one who can merge a PR into the main branch
name: actions_on_main_branch
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'main'

jobs:
  job1:
    name: check_merge_author
    runs-on: ubuntu-latest
    env:
      ALLOWED_AUTHOR: Urias-T
    steps:
      - name: Check merge author
        if: ${{ github.event.action == 'synchronize' && github.actor != env.ALLOWED_AUTHOR }}
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" != "${{ env.ALLOWED_AUTHOR }}" ]]; then
            echo "Only the user with username ${ALLOWED_AUTHOR} is allowed to merge to main branch."
            exit 1

      - name: Merge to main
        if: ${{ github.event.action == 'synchronize' && github.actor == env.ALLOWED_AUTHOR }}
        run: |
          # Additional steps for the merge process if the conditions are met
          git config user.name "${{ github.event.pull_request.user.login }}"
          git config user.email "${{ github.event.pull_request.user.email }}"
          git checkout main
          git merge "${{ github.event.pull_request.head.sha }}"
          # Additional merge steps or actions
